USE [master]
GO

/****** Object:  Database [HNSandbox]    Script Date: 6/8/2020 7:43:12 PM ******/
CREATE DATABASE [HNSandbox] ON  PRIMARY 
( NAME = N'HNSandbox', FILENAME = N'E:\SQLData\HNSandbox.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HNSandbox_log', FILENAME = N'E:\SQLData\HNSandbox_log.ldf' , SIZE = 9216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HNSandbox] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HNSandbox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HNSandbox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HNSandbox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HNSandbox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HNSandbox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HNSandbox] SET ARITHABORT OFF 
GO

ALTER DATABASE [HNSandbox] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HNSandbox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HNSandbox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HNSandbox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HNSandbox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HNSandbox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HNSandbox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HNSandbox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HNSandbox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HNSandbox] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HNSandbox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HNSandbox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HNSandbox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HNSandbox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HNSandbox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HNSandbox] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HNSandbox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HNSandbox] SET RECOVERY FULL 
GO

ALTER DATABASE [HNSandbox] SET  MULTI_USER 
GO

ALTER DATABASE [HNSandbox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HNSandbox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HNSandbox] SET  READ_WRITE 
GO


